name: Build & Deploy

# Only build on main branch
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build_deploy
  cancel-in-progress: true

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15"
        
      - name: Install PNPM & Dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Astro Build
        run: pnpm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
